config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  get "play", to: "games#show"
  resource :user, only: :show

  resources :groups, only: [:show, :create]
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user

  validates :user, presence: true
  validates :token, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :groups

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @group = Group.find_by(token: params[:group])
    ActionCable.server.broadcast 'groups', id: @group.id if @group
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def show
    @group = Group.find(params[:id])
  end

  def create
    @group = current_user.groups.new(token: SecureRandom.urlsafe_base64)
    if @group.save
      flash[:notice] = "Group successfully created."
      redirect_to @group
    else
      flas[:alert] = "Group could NOT be created."
      redirect_to current_user
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/show.html.erb
<%= javascript_include_tag "games" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div id="echo"></div>
    </div>

    <div class="col-md-6">
      <div id="blocklyDiv" style="height: 480px; width: 600px;"></div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <button onclick="runCode()">Run!</button>
    </div>
  </div>
</div>

<xml id="toolbox" style="display: none">
  <block type="echo_walk"></block>
  <block type="echo_jump"></block>
  <block type="echo_turn">
    <field name="turn">right</field>
  </block>
  <block type="echo_turn">
    <field name="turn">left</field>
  </block>
</xml>

<script>
  var workspace = Blockly.inject('blocklyDiv',
      {toolbox: document.getElementById('toolbox')});

  function runCode() {
    var code = Blockly.JavaScript.workspaceToCode(workspace);

    try {
      eval(code);
    } catch (e) {
      alert(e);
    }
  }
</script>

app/views/groups/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Group: <%= @group.token %></h2>
      <h3>URL: <a href="<%=  url_for(controller: :games, action: :show, group: @group.token.to_s) %>"><%=  url_for(controller: :games, action: :show, group: @group.token.to_s) %></a></h3>
      <div id="sessions-<%= @group.id %>"></div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Hello, world!</h1>
    <h1>I'm Echo</h1>
    <br>
    <p><%= link_to "Start Playing!", play_path, class: 'btn btn-primary btn-lg' %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Echo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Echo</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Play!", play_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to 'Hello ' + current_user.email, user_path %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>

  <div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Hello <%= current_user.email %></h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= form_for :group, url: groups_path do |f| %>
        <%= f.submit "Create New Group" %>
      <% end %>
    </div>
    <div class="col-md-12">
      <% current_user.groups.each do |group| %>
        <div><%= link_to "Group: #{group.id}", group_path(group) %></div>
      <% end %>
    </div>
  </div>
</div>